server:
  port: 8081

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:29092,localhost:39092,localhost:49092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.UUIDSerializer
    consumer:
      bootstrap-servers: localhost:29092,localhost:39092,localhost:49092
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
    listener:
      ack-mode: manual_immediate
  datasource:
    state:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/g3
      username: rqm
      password: g3_rqm
    cache:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:g3rqm-db
      username: rqm
      password: g3_rqm
  h2:
    console:
      enabled: true

